### PR TITLE
feat: add cardinality for optional and mandatory features

### PR DESCRIPTION
**Pull request by felixrieg**
Fixes: https://github.com/Universal-Variability-Language/uvl-lsp/issues/44

Read this for more information

### CODE REVIEW

**Comment by pascalfoerster** [comment]
Both Cases which are described in #44 are working. But I think it gives another case which at the moment isn't noted.
If we have mandatory feature with cardinality [0..3], one of three has to be selected. But at the moment it also is returns SAT if nothing is selected.
Fetconf

**Comment by felixrieg** [comment]
@SundermannC  As I understood it, this is the intended behavior.

**Comment by SundermannC** [comment]
Yes, this is intended. I agree that this use case is rather strange, but I think both directions have its merits. Overall, I would still say not being able to select zero features with a cardinality of [0..3] is less intuitive.

**Review by SundermannC — APPROVED** [review]
Behaves as expected!

**Pull request merged**
