### PR TITLE
Issue 104: save complete config in file

### PR DESCRIPTION
**Pull request by felixrieg**
Fixes: #104

When clicking "Save All" it saves every variable, even the ones that got filled by the smt solver

### CODE REVIEW

**Comment by ThiBruUU** [comment]
I don't have a Save-All button in the configurator. I only see the Save button, which saves your own selection of features.

SaveAll

**Comment by felixrieg** [comment]
I am starting to believe, that you don't start the extension from the code. It is not sufficient to load a different UVL.exe. You need to start the extension with F5, if you press F5 a new VSCode instance should spawn with all the changes.

**Comment by felixrieg** [comment]
@ThiBruUU Have you tried it again?

**Comment by ThiBruUU** [comment]
I tried again. The "Save All" button is visible and works for features in my case. I also tried attributes and they weren't saved correctly when saving with the "Save All" button.

**Comment by felixrieg** [comment]
@ThiBruUU Do you mean, that the numbers sometimes differ from what you configured?
Because I could reproduce this on main as well, so maybe this is a bug for a separate issue

**Comment by ThiBruUU** [comment]
yes, exactly. When saving via the normal save, the number attribute was saved correctly. It was only saved with 0 when saving via save all.

**Comment by felixrieg** [comment]
Now I am confused. Is this a Bug exclusive to this issue or not? If so, could you give a detailed example

**Review by ThiBruUU — APPROVED** [review]
i guess i made a mistake in the configuration step and set the feature with the attribute false, so the attribute is 0.0 in the save all action. If the feature is enabled, the correct number for the attribute is set in the json file.

**Pull request merged**
