### PR TITLE
feat: add "generate n configurations" command

### PR DESCRIPTION
**Pull request by felixrieg**
Fixes: #93 

### How to test:

- Execute command "generate n configurations"
- specify how many configurations to generate

try this with different files.

### CODE REVIEW

**Comment by ThiBruUU** [comment]
Command is not available in the Command Palette (Ctrl+Shift+P). It is also not displayed under all UVLS commands. 
Maybe the declaration is still missing somewhere?

Tested on Windows

**Comment by felixrieg** [comment]
@ThiBruUU I tested it myself on windows and I could start the command.
Did you also restart the extension. It is not sufficient to just build the UVL.exe for this issue.

When testing it on windows however, I found a bug, that it did not write the config to a file, which I fixed by now.
But maybe we should also test this on Linux. @SundermannC

**Comment by SundermannC** [comment]
Works for me on Linux.

**Comment by ThiBruUU** [comment]
I tried again and this time it showed me the command. However, the problem for me is still that no corresponding file is created under Windows that contains the configurations.

Furthermore, it might be worth considering if there is a notice that appears for 5 seconds after the command completes, saying that the command was executed successfully or with errors.

**Comment by felixrieg** [comment]
@ThiBruUU can you test it again

**Review by ThiBruUU — APPROVED** [review]
LGTM now. Generate n configurations

**Comment by SundermannC** [comment]
Also still works on Linux.

**Pull request merged**
