### PR TITLE
add Notepad++ Integration of UVLS

### LINKED ISSUE #6: Integration of UVLS in Additional IDEs
As of now, UVLS is integrated in:

- [x] Visual Studio Code
- [x] NeoVim

It would be great to have UVLS integrated into additional IDEs to allow more widespread usage.

### PR DESCRIPTION
**Pull request by TobiUUlm**
fixes #6 
naively added UVLS + UDL for Npp and provided a guide (README.md) that explains how to install it.

Review should include if this installing process works as described.

Possible improvements:
- add arguments when calling the executable. 
- add all features of the UVLS, some don't work yet (e.g. TAUT, UNSAT, ..)

Let me know if these features should be available as well. If so, i will debug / add these features.

### CODE REVIEW

**Comment by pascalfoerster** [comment]
I can't get the server to run. I have already tested several possible paths, and with all of them, the server does not start. I don't know if I am using the wrong path or if NppLspClient is not compatible with Linux.

**Comment by TobiUUlm** [comment]
> I can't get the server to run. I have already tested several possible paths, and with all of them, the server does not start. I don't know if I am using the wrong path or if NppLspClient is not compatible with Linux.

Is it really the server not starting or is the path to the server simply not found? 
The configured server is only started if you select the correct language (uvl) in the language setting where you also add the UDL. Please make sure to save the UDL with the name "uvl" and also select "uvl" for your document. Sometimes it automatically selects "custom language" which will not be recognized by the client and therefore not start the uvls.  
But still, I can imagine that the author of the NppLspClient only tested it on windows machines, so maybe it does not work on Linux.

**Comment by pascalfoerster** [comment]
I think the path to server server is simply not found. 

In the NppLspClient manual, it is explained only for Windows. And since Notepad++ in Linux uses Wine, the path might not be in the typical Linux notation. But I have tested other notations myself, all could not be found. Is there perhaps a log file for the NppLspClient (I could not find one until now)?

> Please make sure to save the UDL with the name "uvl" and also select "uvl" for your document. Sometimes it automatically selects "custom language" which will not be recognized by the client and therefore not start the uvls. Additionally you can toggle the console to see if a path is found or if the server throws some kind of error.

I had set everything like this.

**Comment by TobiUUlm** [comment]
No I've also added a description of how to add UVLS to jetbrain IDEs (like IntelliJ, PyCharm, CLion).  
There was an option of creating a custom Plugin with a Parser built in (which is described [here](https://plugins.jetbrains.com/docs/intellij/custom-language-support.html)) but after a few hours I found it to be way to much functionality being included. Additionally it means a lot of work which we would need to maintain in parallel to the UVLS itself.  

Now I use some simple keyword highlighting + UVLS Support for some features (like it works for Npp).  
We should test if this works on non-windows as well.

**Comment by pascalfoerster** [comment]
It works on Linux and the Eclipse LSP-Client also  works for FeautureIDE.

**Comment by SundermannC** [comment]
I also tested the Eclipse version and it seems to work within the stated limitations. As this is orthogonal to the LSP and should not be critical at all to its stability I will merge the current version. Later, we may think about further improvements.

**Pull request merged**
