### PR TITLE
Add formatting

### PR DESCRIPTION
**Pull request by felixrieg**
This adds auto formatting on save.
I formatted every file once, so there should be no unnecessary changes in future commits
I added a Github action, that will check formatting, build and test for every push.

### CODE REVIEW

**Review by TobiUUlm — CHANGES_REQUESTED** [review]
probably needs to be updated.  
i think you can simply pull the latest master and quickly redo the formatting

**Comment by felixrieg** [comment]
@TobiUUlm can you check again

**Comment by TobiUUlm** [comment]
Looks good

**Review by ThiBruUU — APPROVED** [review]
Looks good to me

**Pull request merged**
