### PR TITLE
feat: type-aware autocomplete

### PR DESCRIPTION
**Pull request by felixrieg**
fixes: #55 

Add type awareness for strings and numericals.
Makes suggestions more context based.

### CODE REVIEW

**Review by pascalfoerster — COMMENTED** [review]
If I have a constraint "2 ==", the autocomplete should suggest real or integer features, but not string features. But you can see in the picture that string features are also suggested. The same problem if the condition starts with a string or a boolean.
Bildschirmfoto vom 2023-08-21 10-35-27

**Comment by felixrieg** [comment]
I improved a lot, but it is still not working for functions and imports

**Review by pascalfoerster — APPROVED** [review]
The only thing that doesn't work is when I have a constraint that starts with "1 <" for example, the autocomplete should actually also show the sum(), avg(), etc. functions.  

As you can see in the picture, the autocomplete is missing the "==". I just don't know if this is part of this problem or if it would be a new problem.
grafik

**Comment by SundermannC** [comment]
If A is a boolean feature in this example, == should not be suggested I think. So, this may be correct behavior.

**Review by pascalfoerster — COMMENTED** [review]
LGTM

**Comment by SundermannC** [comment]
The changes are great. I found two cases where I would expect other suggestions:

len() suggests all(?) references but should only be applicable to string values (features, attributes, constants).

After the boolean operators (e.g., & or |), only features are suggested but a negation "!" would also be possible.

**Pull request merged**
